#include "index_html.h"

const char root_html[] =
    "<!DOCTYPE html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "  <meta charset=\"UTF-8\">\n"
    "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, viewport-fit=cover, user-scalable=no\">\n"
    "  <title>Fire Truck</title>\n"
    "  <style>\n"
    "    :root {\n"
    "      --bg: #0d1117;\n"
    "      --panel: #171b22;\n"
    "      --panel-2: #1d242d;\n"
    "      --stroke: #2f3b45;\n"
    "      --text: #edf2f7;\n"
    "      --muted: #9aa8b5;\n"
    "      --accent: #5cc6d8;\n"
    "      --accent-2: #4fd1a2;\n"
    "      --warn: #ffb347;\n"
    "      --danger: #ff6a6a;\n"
    "      --shadow: rgba(0, 0, 0, 0.22);\n"
    "    }\n"
    "\n"
    "    * { box-sizing: border-box; }\n"
    "\n"
    "    html, body {\n"
    "      margin: 0;\n"
    "      min-height: 100%;\n"
    "      background: var(--bg);\n"
    "      color: var(--text);\n"
    "      font-family: -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif;\n"
    "      -webkit-tap-highlight-color: transparent;\n"
    "    }\n"
    "\n"
    "    body {\n"
    "      display: flex;\n"
    "      justify-content: center;\n"
    "      padding: 10px;\n"
    "      touch-action: manipulation;\n"
    "    }\n"
    "\n"
    "    .app {\n"
    "      width: min(100%, 520px);\n"
    "      display: flex;\n"
    "      flex-direction: column;\n"
    "      gap: 12px;\n"
    "    }\n"
    "\n"
    "    .panel {\n"
    "      background: var(--panel);\n"
    "      border: 1px solid var(--stroke);\n"
    "      border-radius: 16px;\n"
    "      box-shadow: 0 10px 28px var(--shadow);\n"
    "      padding: 12px;\n"
    "    }\n"
    "\n"
    "    .title {\n"
    "      margin: 0;\n"
    "      font-size: 1.2rem;\n"
    "      letter-spacing: 0.03em;\n"
    "      text-align: center;\n"
    "    }\n"
    "\n"
    "    .status {\n"
    "      color: var(--muted);\n"
    "      font-size: 0.78rem;\n"
    "      text-align: center;\n"
    "      min-height: 1em;\n"
    "      margin-top: 4px;\n"
    "    }\n"
    "\n"
    "    .grid {\n"
    "      display: grid;\n"
    "      grid-template-columns: repeat(2, minmax(0, 1fr));\n"
    "      gap: 10px;\n"
    "    }\n"
    "\n"
    "    button {\n"
    "      appearance: none;\n"
    "      border: 1px solid var(--stroke);\n"
    "      border-radius: 12px;\n"
    "      background: var(--panel-2);\n"
    "      color: var(--text);\n"
    "      font-size: 1rem;\n"
    "      font-weight: 600;\n"
    "      min-height: 56px;\n"
    "      padding: 12px 10px;\n"
    "      transition: transform 0.08s ease, background 0.12s ease, border-color 0.12s ease;\n"
    "      touch-action: none;\n"
    "      user-select: none;\n"
    "    }\n"
    "\n"
    "    button:active,\n"
    "    button.active {\n"
    "      transform: scale(0.98);\n"
    "      border-color: var(--accent);\n"
    "      background: rgba(92, 198, 216, 0.18);\n"
    "    }\n"
    "\n"
    "    button.on {\n"
    "      background: rgba(79, 209, 162, 0.18);\n"
    "      border-color: var(--accent-2);\n"
    "    }\n"
    "\n"
    "    .wide {\n"
    "      grid-column: 1 / -1;\n"
    "    }\n"
    "\n"
    "    .controls {\n"
    "      display: grid;\n"
    "      grid-template-columns: repeat(2, minmax(0, 1fr));\n"
    "      gap: 12px;\n"
    "      align-items: center;\n"
    "    }\n"
    "\n"
    "    .drive-panel {\n"
    "      display: grid;\n"
    "      grid-template-columns: 1fr auto 1fr;\n"
    "      align-items: center;\n"
    "      gap: 12px;\n"
    "    }\n"
    "\n"
    "    .joystick-shell {\n"
    "      display: flex;\n"
    "      align-items: center;\n"
    "      justify-content: center;\n"
    "      min-height: 220px;\n"
    "    }\n"
    "\n"
    "    .joystick {\n"
    "      position: relative;\n"
    "      width: min(62vw, 220px);\n"
    "      height: min(62vw, 220px);\n"
    "      border-radius: 50%;\n"
    "      border: 2px solid var(--stroke);\n"
    "      background: radial-gradient(circle at 30% 30%, rgba(255,255,255,0.04), rgba(0,0,0,0.2));\n"
    "      box-shadow: inset 0 0 18px rgba(0,0,0,0.3);\n"
    "      overflow: hidden;\n"
    "      touch-action: none;\n"
    "      user-select: none;\n"
    "    }\n"
    "\n"
    "    .joystick::before {\n"
    "      content: \"\";\n"
    "      position: absolute;\n"
    "      inset: 18%;\n"
    "      border-radius: 50%;\n"
    "      border: 1px solid rgba(255,255,255,0.08);\n"
    "    }\n"
    "\n"
    "    .stick {\n"
    "      position: absolute;\n"
    "      left: 50%;\n"
    "      top: 50%;\n"
    "      width: 34%;\n"
    "      height: 34%;\n"
    "      border-radius: 50%;\n"
    "      border: 2px solid rgba(255,255,255,0.15);\n"
    "      background: linear-gradient(145deg, #2c4250, #1d2731);\n"
    "      box-shadow: 0 8px 18px rgba(0,0,0,0.28);\n"
    "      transform: translate(-50%, -50%);\n"
    "      transition: transform 0.02s linear;\n"
    "    }\n"
    "\n"
    "    .joystick-label {\n"
    "      position: absolute;\n"
    "      font-size: 0.72rem;\n"
    "      color: var(--muted);\n"
    "      letter-spacing: 0.08em;\n"
    "      text-transform: uppercase;\n"
    "      pointer-events: none;\n"
    "    }\n"
    "\n"
    "    .joystick-label.up { top: 10px; left: 50%; transform: translateX(-50%); }\n"
    "    .joystick-label.down { bottom: 10px; left: 50%; transform: translateX(-50%); }\n"
    "    .joystick-label.left { left: 10px; top: 50%; transform: translateY(-50%); }\n"
    "    .joystick-label.right { right: 10px; top: 50%; transform: translateY(-50%); }\n"
    "\n"
    "    .speed-readout {\n"
    "      font-size: 0.82rem;\n"
    "      color: var(--muted);\n"
    "      text-align: center;\n"
    "      margin-top: 8px;\n"
    "    }\n"
    "\n"
    "    .speed-readout strong {\n"
    "      color: var(--text);\n"
    "      font-size: 1.1rem;\n"
    "    }\n"
    "\n"
    "    .vertical-stack {\n"
    "      display: flex;\n"
    "      flex-direction: column;\n"
    "      gap: 10px;\n"
    "      justify-content: center;\n"
    "    }\n"
    "\n"
    "    .tiny {\n"
    "      min-height: 48px;\n"
    "      font-size: 0.9rem;\n"
    "    }\n"
    "\n"
    "    @media (max-width: 360px) {\n"
    "      .grid { grid-template-columns: 1fr; }\n"
    "      .controls { grid-template-columns: 1fr; }\n"
    "      .drive-panel { grid-template-columns: 1fr; }\n"
    "      .vertical-stack { flex-direction: row; justify-content: space-between; }\n"
    "    }\n"
    "  </style>\n"
    "</head>\n"
    "<body>\n"
    "  <div class=\"app\">\n"
    "    <div class=\"panel\">\n"
    "      <h1 class=\"title\">Fire Truck</h1>\n"
    "      <div id=\"status\" class=\"status\" aria-live=\"polite\"></div>\n"
    "    </div>\n"
    "\n"
    "    <div class=\"panel\">\n"
    "      <div class=\"grid\">\n"
    "        <button id=\"engineToggle\" class=\"wide\">🔑 Start engine</button>\n"
    "        <button id=\"lightsToggle\">🚨 Emergency lights</button>\n"
    "        <button id=\"pumpBtn\">💧 Water pump</button>\n"
    "      </div>\n"
    "    </div>\n"
    "\n"
    "    <div class=\"panel\">\n"
    "      <div class=\"grid\">\n"
    "        <button class=\"momentary\" data-endpoint=\"/ladder?cmd=off\" data-press=\"/ladder?cmd=up\">⬆️ Ladder up</button>\n"
    "        <button class=\"momentary\" data-endpoint=\"/ladder?cmd=off\" data-press=\"/ladder?cmd=down\">⬇️ Ladder down</button>\n"
    "        <button class=\"momentary\" data-endpoint=\"/turntable?cmd=off\" data-press=\"/turntable?cmd=left\">⬅️ Turn left</button>\n"
    "        <button class=\"momentary\" data-endpoint=\"/turntable?cmd=off\" data-press=\"/turntable?cmd=right\">➡️ Turn right</button>\n"
    "      </div>\n"
    "    </div>\n"
    "\n"
    "    <div class=\"panel drive-panel\">\n"
    "      <div class=\"vertical-stack\">\n"
    "        <button id=\"brakeBtn\" class=\"tiny\">Brake</button>\n"
    "      </div>\n"
    "\n"
    "      <div>\n"
    "        <div id=\"joystick\" class=\"joystick\" aria-label=\"Drive joystick\">\n"
    "          <span class=\"joystick-label up\">F</span>\n"
    "          <span class=\"joystick-label down\">B</span>\n"
    "          <span class=\"joystick-label left\">L</span>\n"
    "          <span class=\"joystick-label right\">R</span>\n"
    "          <div id=\"stick\" class=\"stick\"></div>\n"
    "        </div>\n"
    "        <div class=\"speed-readout\"><strong id=\"speedValue\">0</strong>%</div>\n"
    "      </div>\n"
    "\n"
    "      <div class=\"vertical-stack\">\n"
    "        <button id=\"coastBtn\" class=\"tiny\">Coast</button>\n"
    "      </div>\n"
    "    </div>\n"
    "  </div>\n"
    "\n"
    "  <script>\n"
    "    const statusEl = document.getElementById('status');\n"
    "    const speedValueEl = document.getElementById('speedValue');\n"
    "    const engineToggle = document.getElementById('engineToggle');\n"
    "    const lightsToggle = document.getElementById('lightsToggle');\n"
    "    const pumpBtn = document.getElementById('pumpBtn');\n"
    "    const brakeBtn = document.getElementById('brakeBtn');\n"
    "    const coastBtn = document.getElementById('coastBtn');\n"
    "    const joystick = document.getElementById('joystick');\n"
    "    const stick = document.getElementById('stick');\n"
    "    const momentaryButtons = document.querySelectorAll('.momentary');\n"
    "\n"
    "    const state = {\n"
    "      engineEnabled: false,\n"
    "      lightsEnabled: false,\n"
    "      pressed: false,\n"
    "      joystickActive: false,\n"
    "      keyboardActive: false,\n"
    "      lastDriveCmd: null,\n"
    "      lastDriveSpeed: 0,\n"
    "      lastSteerCmd: null,\n"
    "      lastBrake: false,\n"
    "      lastPumpPressed: false,\n"
    "      pointerId: null,\n"
    "      keys: {\n"
    "        up: false,\n"
    "        down: false,\n"
    "        left: false,\n"
    "        right: false,\n"
    "        brake: false\n"
    "      }\n"
    "    };\n"
    "\n"
    "    function setStatus(text) {\n"
    "      statusEl.textContent = text || '';\n"
    "    }\n"
    "\n"
    "    const API_BASE_URL = '';\n"
    "\n"
    "    function fetchApi(path) {\n"
    "      const url = /^https?:\\/\\//i.test(path) ? path : API_BASE_URL + (path.startsWith('/') ? path : '/' + path);\n"
    "      return fetch(url, { method: 'GET', cache: 'no-store' })\n"
    "        .then((response) => {\n"
    "          if (!response.ok) {\n"
    "            throw new Error('HTTP ' + response.status);\n"
    "          }\n"
    "        })\n"
    "        .catch((err) => {\n"
    "          console.error('API error:', url, err);\n"
    "          setStatus('Controller unreachable');\n"
    "        });\n"
    "    }\n"
    "\n"
    "    function toggleButtonState(button, active) {\n"
    "      button.classList.toggle('on', active);\n"
    "      button.classList.toggle('active', active);\n"
    "    }\n"
    "\n"
    "    function setMomentaryButton(button, active) {\n"
    "      button.classList.toggle('active', active);\n"
    "    }\n"
    "\n"
    "    engineToggle.addEventListener('click', () => {\n"
    "      state.engineEnabled = !state.engineEnabled;\n"
    "      engineToggle.textContent = state.engineEnabled ? '🛑 Stop engine' : '🔑 Start engine';\n"
    "      engineToggle.classList.toggle('on', state.engineEnabled);\n"
    "      fetchApi(state.engineEnabled ? '/drive?cmd=enable' : '/drive?cmd=disable');\n"
    "      setStatus(state.engineEnabled ? 'Drive enabled' : 'Drive disabled');\n"
    "    });\n"
    "\n"
    "    lightsToggle.addEventListener('click', () => {\n"
    "      state.lightsEnabled = !state.lightsEnabled;\n"
    "      lightsToggle.classList.toggle('on', state.lightsEnabled);\n"
    "      lightsToggle.textContent = state.lightsEnabled ? '🚨 Lights on' : '🚨 Emergency lights';\n"
    "      fetchApi(state.lightsEnabled ? '/emergency_lights?cmd=on' : '/emergency_lights?cmd=off');\n"
    "      setStatus(state.lightsEnabled ? 'Emergency lights on' : 'Emergency lights off');\n"
    "    });\n"
    "\n"
    "    pumpBtn.addEventListener('pointerdown', (event) => {\n"
    "      event.preventDefault();\n"
    "      if (state.lastPumpPressed) return;\n"
    "      state.lastPumpPressed = true;\n"
    "      setMomentaryButton(pumpBtn, true);\n"
    "      fetchApi('/pump?cmd=on');\n"
    "      setStatus('Pump on');\n"
    "    });\n"
    "\n"
    "    const releasePump = () => {\n"
    "      if (!state.lastPumpPressed) return;\n"
    "      state.lastPumpPressed = false;\n"
    "      setMomentaryButton(pumpBtn, false);\n"
    "      fetchApi('/pump?cmd=off');\n"
    "      setStatus('Pump off');\n"
    "    };\n"
    "\n"
    "    pumpBtn.addEventListener('pointerup', releasePump);\n"
    "    pumpBtn.addEventListener('pointerleave', releasePump);\n"
    "    pumpBtn.addEventListener('pointercancel', releasePump);\n"
    "\n"
    "    momentaryButtons.forEach((button) => {\n"
    "      const pressUrl = button.dataset.press;\n"
    "      const offUrl = button.dataset.endpoint;\n"
    "\n"
    "      button.addEventListener('pointerdown', (event) => {\n"
    "        event.preventDefault();\n"
    "        setMomentaryButton(button, true);\n"
    "        fetchApi(pressUrl);\n"
    "        setStatus(button.textContent.trim());\n"
    "      });\n"
    "\n"
    "      const release = () => {\n"
    "        setMomentaryButton(button, false);\n"
    "        if (offUrl) fetchApi(offUrl);\n"
    "      };\n"
    "\n"
    "      button.addEventListener('pointerup', release);\n"
    "      button.addEventListener('pointerleave', release);\n"
    "      button.addEventListener('pointercancel', release);\n"
    "    });\n"
    "\n"
    "    brakeBtn.addEventListener('pointerdown', (event) => {\n"
    "      event.preventDefault();\n"
    "      if (state.lastBrake) return;\n"
    "      state.lastBrake = true;\n"
    "      setMomentaryButton(brakeBtn, true);\n"
    "      fetchApi('/drive?cmd=brake');\n"
    "      setStatus('Brake engaged');\n"
    "    });\n"
    "\n"
    "    const releaseBrake = () => {\n"
    "      if (!state.lastBrake) return;\n"
    "      state.lastBrake = false;\n"
    "      setMomentaryButton(brakeBtn, false);\n"
    "      fetchApi('/drive?cmd=coast');\n"
    "      setStatus('Brake released');\n"
    "    };\n"
    "\n"
    "    brakeBtn.addEventListener('pointerup', releaseBrake);\n"
    "    brakeBtn.addEventListener('pointerleave', releaseBrake);\n"
    "    brakeBtn.addEventListener('pointercancel', releaseBrake);\n"
    "\n"
    "    coastBtn.addEventListener('click', () => {\n"
    "      fetchApi('/drive?cmd=coast');\n"
    "      fetchApi('/steer?cmd=off');\n"
    "      state.lastDriveCmd = 'coast';\n"
    "      state.lastSteerCmd = 'off';\n"
    "      setStatus('Coasting');\n"
    "    });\n"
    "\n"
    "    function clamp(value, min, max) {\n"
    "      return Math.min(Math.max(value, min), max);\n"
    "    }\n"
    "\n"
    "    function mapSpeed(value) {\n"
    "      const normalized = clamp(Math.abs(value), 0, 1);\n"
    "      return Math.round(200 + (normalized * 200));\n"
    "    }\n"
    "\n"
    "    function updateJoystickPosition(x, y) {\n"
    "      const rect = joystick.getBoundingClientRect();\n"
    "      const centerX = rect.left + rect.width / 2;\n"
    "      const centerY = rect.top + rect.height / 2;\n"
    "      const maxRadius = rect.width * 0.33;\n"
    "      const dx = clamp(x - centerX, -maxRadius, maxRadius);\n"
    "      const dy = clamp(y - centerY, -maxRadius, maxRadius);\n"
    "      const distance = Math.hypot(dx, dy);\n"
    "      const limitedX = distance > maxRadius ? (dx / distance) * maxRadius : dx;\n"
    "      const limitedY = distance > maxRadius ? (dy / distance) * maxRadius : dy;\n"
    "\n"
    "      stick.style.left = '50%';\n"
    "      stick.style.top = '50%';\n"
    "      stick.style.transform = `translate(calc(-50% + ${limitedX}px), calc(-50% + ${limitedY}px))`;\n"
    "      return { dx: limitedX, dy: limitedY, maxRadius };\n"
    "    }\n"
    "\n"
    "    function sendDriveAndSteer(rawX, rawY) {\n"
    "      const maxRadius = joystick.getBoundingClientRect().width * 0.33;\n"
    "      const dx = clamp(rawX, -maxRadius, maxRadius);\n"
    "      const dy = clamp(rawY, -maxRadius, maxRadius);\n"
    "      const effectiveDy = -dy;\n"
    "      const steerThreshold = maxRadius * 0.2;\n"
    "      const driveThreshold = maxRadius * 0.12;\n"
    "\n"
    "      let driveCmd = 'coast';\n"
    "      let speedValue = 0;\n"
    "\n"
    "      if (effectiveDy > driveThreshold) {\n"
    "        driveCmd = 'forward';\n"
    "        speedValue = mapSpeed(Math.abs(effectiveDy) / maxRadius);\n"
    "      } else if (effectiveDy < -driveThreshold) {\n"
    "        driveCmd = 'reverse';\n"
    "        speedValue = mapSpeed(Math.abs(effectiveDy) / maxRadius);\n"
    "      }\n"
    "\n"
    "      let steerCmd = 'off';\n"
    "      if (dx > steerThreshold) steerCmd = 'right';\n"
    "      else if (dx < -steerThreshold) steerCmd = 'left';\n"
    "\n"
    "      if (driveCmd !== state.lastDriveCmd || speedValue !== state.lastDriveSpeed) {\n"
    "        if (driveCmd === 'coast') {\n"
    "          fetchApi('/drive?cmd=coast');\n"
    "        } else {\n"
    "          fetchApi('/drive?cmd=' + driveCmd + '&speed=' + speedValue);\n"
    "        }\n"
    "        state.lastDriveCmd = driveCmd;\n"
    "        state.lastDriveSpeed = speedValue;\n"
    "      }\n"
    "\n"
    "      if (steerCmd !== state.lastSteerCmd) {\n"
    "        fetchApi('/steer?cmd=' + steerCmd);\n"
    "        state.lastSteerCmd = steerCmd;\n"
    "      }\n"
    "\n"
    "      const displaySpeed = driveCmd === 'coast' ? 0 : Math.min(100, Math.round((speedValue / 400) * 100));\n"
    "      speedValueEl.textContent = String(displaySpeed);\n"
    "      setStatus(driveCmd === 'coast' ? 'Driving idle' : driveCmd + ' @ ' + speedValue + '');\n"
    "    }\n"
    "\n"
    "    function applyKeyboardMovement() {\n"
    "      const up = state.keys.up || false;\n"
    "      const down = state.keys.down || false;\n"
    "      const left = state.keys.left || false;\n"
    "      const right = state.keys.right || false;\n"
    "      const brakePressed = state.keys.brake || false;\n"
    "\n"
    "      if (brakePressed) {\n"
    "        if (!state.lastBrake) {\n"
    "          state.lastBrake = true;\n"
    "          setMomentaryButton(brakeBtn, true);\n"
    "          fetchApi('/drive?cmd=brake');\n"
    "          setStatus('Brake engaged');\n"
    "        }\n"
    "        speedValueEl.textContent = '0';\n"
    "        return;\n"
    "      }\n"
    "\n"
    "      if (state.lastBrake) {\n"
    "        state.lastBrake = false;\n"
    "        setMomentaryButton(brakeBtn, false);\n"
    "        fetchApi('/drive?cmd=coast');\n"
    "      }\n"
    "\n"
    "      const dx = (right ? 1 : 0) - (left ? 1 : 0);\n"
    "      const dy = (up ? 1 : 0) - (down ? 1 : 0);\n"
    "\n"
    "      if (dx === 0 && dy === 0) {\n"
    "        if (state.lastDriveCmd !== 'coast' || state.lastSteerCmd !== 'off') {\n"
    "          fetchApi('/drive?cmd=coast');\n"
    "          fetchApi('/steer?cmd=off');\n"
    "          state.lastDriveCmd = 'coast';\n"
    "          state.lastSteerCmd = 'off';\n"
    "          state.lastDriveSpeed = 0;\n"
    "          speedValueEl.textContent = '0';\n"
    "          setStatus('Driving idle');\n"
    "        }\n"
    "        return;\n"
    "      }\n"
    "\n"
    "      let driveCmd = 'coast';\n"
    "      let speedValue = 0;\n"
    "      if (dy > 0) {\n"
    "        driveCmd = 'forward';\n"
    "        speedValue = 350;\n"
    "      } else if (dy < 0) {\n"
    "        driveCmd = 'reverse';\n"
    "        speedValue = 350;\n"
    "      }\n"
    "\n"
    "      let steerCmd = 'off';\n"
    "      if (dx > 0) steerCmd = 'right';\n"
    "      else if (dx < 0) steerCmd = 'left';\n"
    "\n"
    "      if (driveCmd !== state.lastDriveCmd || speedValue !== state.lastDriveSpeed) {\n"
    "        if (driveCmd === 'coast') {\n"
    "          fetchApi('/drive?cmd=coast');\n"
    "        } else {\n"
    "          fetchApi('/drive?cmd=' + driveCmd + '&speed=' + speedValue);\n"
    "        }\n"
    "        state.lastDriveCmd = driveCmd;\n"
    "        state.lastDriveSpeed = speedValue;\n"
    "      }\n"
    "\n"
    "      if (steerCmd !== state.lastSteerCmd) {\n"
    "        fetchApi('/steer?cmd=' + steerCmd);\n"
    "        state.lastSteerCmd = steerCmd;\n"
    "      }\n"
    "\n"
    "      const displaySpeed = Math.min(100, Math.round((speedValue / 400) * 100));\n"
    "      speedValueEl.textContent = String(displaySpeed);\n"
    "      setStatus(driveCmd === 'coast' ? 'Driving idle' : driveCmd + ' @ ' + speedValue + '');\n"
    "    }\n"
    "\n"
    "    function resetJoystick() {\n"
    "      state.joystickActive = false;\n"
    "      stick.style.transform = 'translate(-50%, -50%)';\n"
    "      state.lastDriveCmd = null;\n"
    "      state.lastDriveSpeed = 0;\n"
    "      state.lastSteerCmd = null;\n"
    "      speedValueEl.textContent = '0';\n"
    "      fetchApi('/drive?cmd=coast');\n"
    "      fetchApi('/steer?cmd=off');\n"
    "      setStatus('Joystick reset');\n"
    "    }\n"
    "\n"
    "    joystick.addEventListener('pointerdown', (event) => {\n"
    "      event.preventDefault();\n"
    "      state.joystickActive = true;\n"
    "      state.pointerId = event.pointerId;\n"
    "      joystick.setPointerCapture(event.pointerId);\n"
    "      const pos = updateJoystickPosition(event.clientX, event.clientY);\n"
    "      sendDriveAndSteer(pos.dx, pos.dy);\n"
    "    });\n"
    "\n"
    "    joystick.addEventListener('pointermove', (event) => {\n"
    "      if (!state.joystickActive || event.pointerId !== state.pointerId) return;\n"
    "      const pos = updateJoystickPosition(event.clientX, event.clientY);\n"
    "      sendDriveAndSteer(pos.dx, pos.dy);\n"
    "    });\n"
    "\n"
    "    function handleJoystickRelease(event) {\n"
    "      if (!state.joystickActive) return;\n"
    "      if (event && event.pointerId !== undefined && event.pointerId !== state.pointerId) return;\n"
    "      resetJoystick();\n"
    "      joystick.releasePointerCapture?.(state.pointerId);\n"
    "      state.pointerId = null;\n"
    "    }\n"
    "\n"
    "    joystick.addEventListener('pointerup', handleJoystickRelease);\n"
    "    joystick.addEventListener('pointercancel', handleJoystickRelease);\n"
    "    joystick.addEventListener('pointerleave', () => {\n"
    "      if (!state.joystickActive) return;\n"
    "      handleJoystickRelease();\n"
    "    });\n"
    "\n"
    "    function handleKeyChange(event, pressed) {\n"
    "      const key = event.key.toLowerCase();\n"
    "      if (key === 'arrowup' || key === 'w') state.keys.up = pressed;\n"
    "      if (key === 'arrowdown' || key === 's') state.keys.down = pressed;\n"
    "      if (key === 'arrowleft' || key === 'a') state.keys.left = pressed;\n"
    "      if (key === 'arrowright' || key === 'd') state.keys.right = pressed;\n"
    "      if (key === ' ') state.keys.brake = pressed;\n"
    "\n"
    "      if (pressed) {\n"
    "        state.keyboardActive = true;\n"
    "      } else if (!state.keys.up && !state.keys.down && !state.keys.left && !state.keys.right && !state.keys.brake) {\n"
    "        state.keyboardActive = false;\n"
    "      }\n"
    "\n"
    "      if (state.keys.brake) {\n"
    "        if (!state.lastBrake) {\n"
    "          state.lastBrake = true;\n"
    "          setMomentaryButton(brakeBtn, true);\n"
    "          fetchApi('/drive?cmd=brake');\n"
    "          setStatus('Brake engaged');\n"
    "        }\n"
    "        speedValueEl.textContent = '0';\n"
    "        return;\n"
    "      }\n"
    "\n"
    "      if (state.lastBrake) {\n"
    "        state.lastBrake = false;\n"
    "        setMomentaryButton(brakeBtn, false);\n"
    "        fetchApi('/drive?cmd=coast');\n"
    "      }\n"
    "\n"
    "      if (state.keyboardActive) {\n"
    "        applyKeyboardMovement();\n"
    "      } else if (!state.joystickActive) {\n"
    "        fetchApi('/drive?cmd=coast');\n"
    "        fetchApi('/steer?cmd=off');\n"
    "        state.lastDriveCmd = 'coast';\n"
    "        state.lastDriveSpeed = 0;\n"
    "        state.lastSteerCmd = 'off';\n"
    "        speedValueEl.textContent = '0';\n"
    "      }\n"
    "    }\n"
    "\n"
    "    document.addEventListener('keydown', (event) => {\n"
    "      if (['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','w','W','a','A','s','S','d','D'].includes(event.key)) {\n"
    "        event.preventDefault();\n"
    "      }\n"
    "      handleKeyChange(event, true);\n"
    "    });\n"
    "\n"
    "    document.addEventListener('keyup', (event) => {\n"
    "      handleKeyChange(event, false);\n"
    "    });\n"
    "  </script>\n"
    "</body>\n"
    "</html>\n"
;
